name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - sos-essentials
  - conda
  - python=3.7
  - pip
  - jupyterhub
  - notebook
  - jupyterlab
  - matplotlib-base
  - cloudpickle
  - numba
  - conda-forge::blas[build=openblas]
  - sqlalchemy
  - cython
  - vincent
  - dask
  - seaborn
  - statsmodels
  - xlrd
  - scipy
  - scikit-learn
  - hdf5
  - sympy
  - pandas
  - beautifulsoup4
  - bokeh
  - ipywidgets
  - patsy
  - dill
  - h5py
  - protobuf
  - numexpr
  - scikit-image
  - r-htmlwidgets
  - r-shiny
  - r-forecast
  - r-htmltools
  - r-devtools
  - r-caret
  - r-randomforest
  - r-nycflights13
  - r-base
  - r-tidyverse
  - r-rsqlite
  - rpy2
  - r-irkernel
  - r-plyr
  - r-hexbin
  - r-rmarkdown
  - r-rcurl
  - r-reshape2
  - r-crayon
  - jupytext
  - conda-forge::r-europepmc

